### ISSUE TITLE
PCB Details

### ISSUE THREAD

**Issue by oollie34** [ABangingDonk/OpenHaldexT4#1]
Could you provide any more info regarding the 4 daughter boards you have connected to your PCB? Plus wiring for them etc.
I'd be interested in doing a single board design, which I will provide here.

**Comment by ABangingDonk** [comment]
There's 4 boards in total:

1. Base board designed for this project
2. Teensy 4.0 (or 4.1)
3. HC-05 bluetooth serial module
4. DC buck converter

I've just committed the EasyEDA project files

**Comment by oollie34** [comment]
Will take a look, thanks!
