### ISSUE TITLE
Abs lamp

### ISSUE THREAD

**Issue by drtapfesz** [ABangingDonk/OpenHaldexT4#4]
Hello!  I put together the project, the bluetooth software is connected to the device, I can see the gas pedal position in live data and it operates the haldex.  my problem is that the front light and the abs light keep flashing.  an indelible error code is created in the engine controller, which is a P1650 missing message from the drive chain.  maybe you have an idea as to what could be causing this, since I can also diagnose the haldex, this assumes for me that he is on the network.  I connected the electronics to the trunk near the spare wheel.

**Comment by ABangingDonk** [comment]
The fact that you can see pedal position in the app but also see this error code implies to me that the CAN connection between OpenHaldex and the Haldex controller is not good.

This assumes that the CAN messages sent from Haldex are getting forwarded to the chassis side as per unmodified Teensy firmware.

Haldex diagnosis is via K-line, not via CAN so this doesn't necessarily mean it's all connected properly.

**Comment by drtapfesz** [comment]
Hello!  It's really K-line, I forgot about the diag line.  Knitting is not too difficult, in principle Can-H is orange-black and Can-L is orange-brown.  The PCB (4.0) chassis is in car, Haldex in haldex.  And I completed the Teensy program from here.

**Comment by ABangingDonk** [comment]
If you recompile the firmware with CAN1_DEBUG set to 1 then you should be able to get debug information out of the Teensy via USB serial - this will print all of the messages that the Haldex side is receiving (messages that the ECU is expecting). Can you check this please?

**Comment by drtapfesz** [comment]
Ok!

Thanks for helping 🙂

**Comment by drtapfesz** [comment]
Hi! Serial log.
I see haldex tx problem.

![PXL_20241118_112815393](https://github.com/user-attachments/assets/c8297a46-ec1f-486b-8156-6096e77ea716)

**Comment by drtapfesz** [comment]
Hello!  I found it, fixed it.  I checked the terminating resistor of the Can network.
